name: deploy-container

on:
  push:
    branches: 
      - master
    paths: 
      - 'packages/container/**'

defaults: 
  run:
    working-directory: packages/container

jobs:
  builds: 
    steps: 
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses:
      - run: 